# Generated by Django 4.0.3 on 2022-03-31 06:59

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=20, unique=True)),
                ('nickname', models.CharField(max_length=100, unique=True)),
                ('point', models.BigIntegerField(default=0)),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='mypage_images/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
