# Generated by Django 4.0.3 on 2022-03-29 02:50

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='city_images/'),
        ),
    ]
