# Generated by Django 4.0.3 on 2022-04-05 07:31

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_city_background_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='background_photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='back_images/'),
        ),
    ]
