# Generated by Django 4.0.3 on 2022-04-05 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasons', models.IntegerField(choices=[(1, '봄'), (2, '여름'), (3, '가을'), (4, '겨울')], null=True)),
                ('mnt_sea', models.IntegerField(choices=[(5, '산'), (6, '바다')], null=True)),
                ('urb_rur', models.IntegerField(choices=[(7, '도시'), (8, '시골')], null=True)),
                ('comp', models.IntegerField(choices=[(9, '혼자'), (10, '친구'), (11, '연인'), (12, '가족')], null=True)),
                ('impo', models.IntegerField(choices=[(13, '풍경'), (14, '음식'), (15, '액티비티'), (16, '힐링')], null=True)),
                ('paint', models.IntegerField(choices=[(17, '별이 빛나는 밤'), (18, '그랑드자트섬의 일요일 오후'), (19, '메모리 지속성의 붕괴'), (20, '민중을 이끄는 자유의 여신')], null=True)),
                ('movie', models.IntegerField(choices=[(21, '기생충'), (22, '토이스토리'), (23, '인터스텔라'), (24, '건축학개론'), (25, '분노의 질주'), (26, '극한직업')], null=True)),
                ('trans', models.IntegerField(choices=[(27, '자가용'), (28, '대중교통'), (29, '도보')], null=True)),
                ('plan', models.IntegerField(choices=[(30, '계획적'), (31, '즉흥적')], null=True)),
                ('mor_eve', models.IntegerField(choices=[(32, '아침형 인간'), (33, '저녁형 인간')], null=True)),
                ('results', models.JSONField(default=None, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taste', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
