# Generated by Django 4.0.3 on 2022-03-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taste',
            name='comp',
            field=models.IntegerField(choices=[(9, '혼자'), (10, '친구'), (11, '연인'), (12, '가족')], null=True),
        ),
        migrations.AlterField(
            model_name='taste',
            name='impo',
            field=models.IntegerField(choices=[(13, '풍경'), (14, '음식'), (15, '액티비티'), (16, '힐링')], null=True),
        ),
        migrations.AlterField(
            model_name='taste',
            name='mnt_sea',
            field=models.IntegerField(choices=[(5, '산'), (6, '바다')], null=True),
        ),
        migrations.AlterField(
            model_name='taste',
            name='mor_eve',
            field=models.IntegerField(choices=[(32, '아침형 인간'), (33, '저녁형 인간')], null=True),
        ),
        migrations.AlterField(
            model_name='taste',
            name='movie',
            field=models.IntegerField(choices=[(21, '기생충'), (22, '토이스토리'), (23, '인터스텔라'), (24, '건축학개론'), (25, '분노의 질주'), (26, '극한직업')], null=True),
        ),
        migrations.AlterField(
            model_name='taste',
            name='paint',
            field=models.IntegerField(choices=[(17, '별이 빛나는 밤'), (18, '그랑드자트섬의 일요일 오후'), (19, '메모리 지속성의 붕괴'), (20, '민중을 이끄는 자유의 여신')], null=True),
        ),
        migrations.AlterField(
            model_name='taste',
            name='plan',
            field=models.IntegerField(choices=[(30, '계획적'), (31, '즉흥적')], null=True),
        ),
        migrations.AlterField(
            model_name='taste',
            name='seasons',
            field=models.IntegerField(choices=[(1, '봄'), (2, '여름'), (3, '가을'), (4, '겨울')], null=True),
        ),
        migrations.AlterField(
            model_name='taste',
            name='trans',
            field=models.IntegerField(choices=[(27, '자가용'), (28, '대중교통'), (29, '도보')], null=True),
        ),
        migrations.AlterField(
            model_name='taste',
            name='urb_rur',
            field=models.IntegerField(choices=[(7, '도시'), (8, '시골')], null=True),
        ),
    ]
